#!/bin/sh
echo "Formatting java code..."
./mvnw com.coveo:fmt-maven-plugin:format 1> /dev/null
echo "Formatting js code..."
npm --prefix frontend/ run precise-commits 1> /dev/null

# read files that could potentially have been reformatted
git diff --cached --name-status | sed 's/^.*[[:space:]]//' | xargs git add
