dist: trusty
notifications:
    email: false
sudo: required
cache: inst

jobs:
    include:
        - stage: prepare cache
          script:
              - ./mwvn -DskipTests=true install
        - stage: test
          script:
              - ./mvnw test verify
        - stage: publish
          #if: branch = master
          script:
              #- ./mvnw -DskipTests=true package
              - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              - docker build -t hunter -f docker/Dockerfile-Prod .
              - docker images
              - docker tag hunter japt/hunter
              - docker push japt/hunter
