dist: trusty
notifications:
    email: false
sudo: required
cache:
    directories:
        - $HOME/.m2
        - backend/target

addons:
    sonarcloud:
        organization: sbi-github

jobs:
    include:
        - stage: prepare cache
          script:
              - ./mvnw -DskipTests=true clean install
        - stage: test
          script:
              - ./mvnw test verify
        - stage: sonar
          script:
              - sonar-scanner
        - stage: publish
          if: branch = master
          script:
              - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              - docker build -t hunter -f docker/Dockerfile-Prod .
              - docker images
              - docker tag hunter japt/hunter
              - docker push japt/hunter
