language: java
notifications:
    email: false
sudo: true

jobs:
    include:
        - stage: build
          script:
              - ./mvnw -DskipTests=true package
          -stage: test
           script:
              - ./mnvw test verify
