# slimmer container may be possible
# will want to test with alpine
FROM openjdk:8-slim
# use maven docker plugin for generating this
COPY ./backend/target/*.jar /app/hunter.jar
WORKDIR /app
EXPOSE 8080
EXPOSE 8443
CMD ["java", "-jar", "/app/hunter.jar"]
