# slimmer container may be possible
# will want to test with alpine
FROM openjdk:8-slim
# use maven docker plugin for generating this
COPY ./backend/target/backend-0.0.1-SNAPSHOT.jar /app/hunter.jar
WORKDIR /app
EXPOSE 8080
EXPOSE 8443
RUN /usr/lib/jvm/java-8-openjdk-amd64/bin/keytool -genkey -noprompt \
     -alias tomcat \
     -dname "CN=sinv-56053.edu.hsr.ch, OU=ID, O=japt, C=CH" \
     -keystore /app/keystore.p12 \
     -storepass default \
     -storetype PKCS12 \
     -keyalg RSA \
     -keysize 2048 \
     -keypass default
CMD ["java", "-jar", "/app/hunter.jar"]
