version: '3.3'

services:
    hunter:
        build:
            context: ../
            # create docker file from template and refer to it here?
            dockerfile: docker/Dockerfile-Prod
        ports:
            - '8080:8080'
            - '8443:8443'
        depends_on:
            - db
        environment:
          SPRING_PROFILES_ACTIVE: test
        restart: always


    db:
      # this will have to be a dockerfile as well, which then runs db creation
      # and stuff like that. Secrets should be read from a file
      image: postgres
      restart: always
      environment:
          POSTGRES_PASSWORD: example
